controllers/PublicarController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use app\models\UploadImages;
use app\models\Ciudades;
use app\models\Estados;
use app\models\Publicacion;
use app\models\OwnerInformation;
use app\models\InformationPublication;
use app\models\User;
use yii\web\UploadedFile;
use app\models\TipoAnuncio;
use kartik\growl\Growl;
use app\components\AccessRule;

class PublicarController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    
    public function actionUpload()
    {
        $rol = Yii::$app->user->identity->type_user_id;
        if($rol == 1)
        {
            $model = new UploadImages();
            $modelCiudades = new Ciudades();
            $modelEstado = Estados::find()->orderBy('id')->all();
            $modelPublcacion = new Publicacion;
            $estado = new Estados;
            $ciudades = new Ciudades;
            $tipo = new TipoAnuncio();
            $modelTipoPublicacion = TipoAnuncio::find()->orderBy('id')->all();
            if (Yii::$app->request->isPost) 
            {
                $connection = \Yii::$app->db;
                $transaction = $connection->beginTransaction();

                try
                {

                    $post = Yii::$app->request->post();
                    $modelInformationOwner = new OwnerInformation();
                    $modelInformation = new InformationPublication();
                    $modelInformation->nombreEdificio = $post["Publicacion"]["nombreEdificio"];
                    $modelInformation->piso = $post["Publicacion"]["piso"];
                    $modelInformation->costo = $post["Publicacion"]["costo"];
                    $modelInformation->metros = $post["Publicacion"]["metros"];
                    $modelInformation->cuartos = $post["Publicacion"]["cuartos"];
                    $modelInformation->banos = $post["Publicacion"]["banos"];
                    $modelInformation->estacionamiento = $post["Publicacion"]["estacionamiento"];
                    $modelInformation->antiguedad = $post["Publicacion"]["antiguedad"];
                    if ($modelInformation->save())
                    {

                        $modelPublcacion->information = $modelInformation->id;
                        $modelInformationOwner->nombre=  $post["Publicacion"]["nombre"];
                        $modelInformationOwner->cedula=  $post["Publicacion"]["cedula"];
                        $modelInformationOwner->telefonoLocal=  $post["Publicacion"]["telefonoLocal"];
                        $modelInformationOwner->telefonoCelular=  $post["Publicacion"]["telefonoCelular"];
                        $modelInformationOwner->correo=  $post["Publicacion"]["correo"];
                        if($modelInformationOwner->save())
                        {   
                            $modelPublcacion->owner_information = $modelInformationOwner->id;
                            $modelPublcacion->id_ciudad=$post["Ciudades"]["Ciudades"];
                            $modelPublcacion->id_tipo_anuncio = $post["TipoAnuncio"]["tipo_anuncio"];
                            $modelPublcacion->create_date = date("Y-m-d");
                            if($modelPublcacion->save())
                            {
                                $model->imageFiles = UploadedFile::getInstances($model, 'imageFiles');
                                if ($model->upload($modelPublcacion->id,$post["Ciudades"]["Ciudades"])) 
                                {

                                    $transaction->commit();
                                    $model = new UploadImages();
                                    $modelCiudades = new Ciudades();
                                    $modelEstado = Estados::find()->orderBy('id')->all();
                                    $modelPublcacion = new Publicacion;
                                    $estado = new Estados;
                                    $ciudades = new Ciudades;
                                    $tipo = new TipoAnuncio();
                                    $modelTipoPublicacion = TipoAnuncio::find()->orderBy('id')->all();
                                    \Yii::$app->getSession()->setFlash('success',[
                                                                        'type' => Growl::TYPE_SUCCESS,
                                                                        'title' => 'Guardado',
                                                                        'icon' => 'glyphicon glyphicon-info-sign',
                                                                        'body' => 'Se ha guardado todo con exito',
                                                                        'showSeparator' => true,
                                                                        'delay' => 1500,
                                                                        'pluginOptions' => [
                                                                            'showProgressbar' => true,
                                                                        'placement' => [
                                                                            'from' => 'top',
                                                                            'align' => 'right',
                                                                            ]
                                                                        ]
                                                                ]);
                                }
                                else
                                {
                                    $transaction->rollBack();
                                    \Yii::$app->getSession()->setFlash('error', [
                                                                        'type' => Growl::TYPE_WARNING,
                                                                        'title' => 'Error',
                                                                        'icon' => 'glyphicon glyphicon-info-sign',
                                                                        'body' => 'Falla al subir las imagenes',
                                                                        'showSeparator' => true,
                                                                        'delay' => 1500,
                                                                        'pluginOptions' => [
                                                                            'showProgressbar' => true,
                                                                        'placement' => [
                                                                            'from' => 'top',
                                                                            'align' => 'right',
                                                                            ]
                                                                        ]
                                                                ]);
                                }

                            }
                            else
                            {
                                $transaction->rollBack();
                                \Yii::$app->getSession()->setFlash('error',[
                                                                    'type' => Growl::TYPE_WARNING,
                                                                    'title' => 'Error!',
                                                                    'icon' => 'glyphicon glyphicon-info-sign',
                                                                    'body' => 'Falla General al cargar la informacion',
                                                                    'showSeparator' => true,
                                                                    'delay' => 1500,
                                                                    'pluginOptions' => [
                                                                        'showProgressbar' => true,
                                                                    'placement' => [
                                                                        'from' => 'top',
                                                                        'align' => 'right',
                                                                        ]
                                                                    ]
                                                                ]);
                            }
                        }
                        else
                        {
                            $transaction->rollBack();
                        }
                    }
                    else
                    {
                        $transaction->rollBack();
                    }

                } catch (Exception $ex) {
                    $transaction->rollBack();
                    var_dump($ex);
                }
            }

            return $this->render('upload', [
                'model' => $model,
                'modelCiudades' => $modelCiudades,
                'modelEstado' => $modelEstado,
                'estado'=>$estado,
                'ciudades'=>$ciudades,
                'tipo' => $tipo,
                'publicacion'=>$modelPublcacion,
                'tipoPublicacion'=>$modelTipoPublicacion,
                    ]);   
        }
        else
        {
            return $this->render('site/permission');
        }

    }
    
    public function actionVentas()
    {
        $ventas = Publicacion::getAllSales();
        
        if (empty($ventas))
        {
            $ventas = NULL;
        }

        
        return $this->render('ventas',[
            'ventas' => $ventas
            ]);
    }
    
    public function actionAlquiler()

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\User;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
 
    NavBar::begin([
        'brandLabel' => '<div style="margin-top: -10px;"><img width="45" class="pull-left"  src="/images/logo___copia_1.png"/></div>'.'<div style="margin-top: 10px; margin-left: 55px;"> INMOBILIARIA PRADO 2010, C. A.</div>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    
    
    if (Yii::$app->user->isGuest) {
        $menuItems = [
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'About', 'url' => ['/site/about']],
                ['label' => 'Contact', 'url' => ['/site/contact']],
                ['label' => 'Publicaciones', 'items' => [
                                ['label' => 'Ventas', 'url' => ['/publicar/ventas']],
                                ['label' => 'Alquiler', 'url' => ['/publicar/alquiler']],
                                ],],
            ];
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        if (Yii::$app->user->identity->type_user_id == 1)
        {
            $menuItems[] = ['label'=> 'Residencias','url' => ['/residencias']];
             $menuItems[] = 
                    ['label' => 'Publicar', 'url' => ['/publicar/upload']
                 ];
        }
        $menuItems[] = [
            'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']];
        
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>
    
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <div class="container">
        <p class="pull-left">&copy;INMOBILIARIA PRADO 2010, C. A. <?= date('Y') ?></p>
        <p class="pull-right"><?= "Hecho por Ady A. Prado S."; ?></p>
    </div>
</footer>
   
<?php $this->endBody() ?>

     <script>
        jQuery(document).ready(function () {
            $CONDOMINIO.UI.init();
        });
    </script>
</body>
</html>
<?php $this->endPage() ?>